//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.24 at 01:07:46 AM CEST 
//


package metier.webapp.persistence.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the metier.webapp.persistence.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Author_QNAME = new QName("", "author");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _CreatedDate_QNAME = new QName("", "createdDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: metier.webapp.persistence.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OutputList }
     * 
     */
    public OutputList createOutputList() {
        return new OutputList();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link Tools }
     * 
     */
    public Tools createTools() {
        return new Tools();
    }

    /**
     * Create an instance of {@link CategoryMap }
     * 
     */
    public CategoryMap createCategoryMap() {
        return new CategoryMap();
    }

    /**
     * Create an instance of {@link UseTestCheck }
     * 
     */
    public UseTestCheck createUseTestCheck() {
        return new UseTestCheck();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link LogoutCheck }
     * 
     */
    public LogoutCheck createLogoutCheck() {
        return new LogoutCheck();
    }

    /**
     * Create an instance of {@link CreateTestCheck }
     * 
     */
    public CreateTestCheck createCreateTestCheck() {
        return new CreateTestCheck();
    }

    /**
     * Create an instance of {@link UseTestVerify }
     * 
     */
    public UseTestVerify createUseTestVerify() {
        return new UseTestVerify();
    }

    /**
     * Create an instance of {@link ReadTestVerify }
     * 
     */
    public ReadTestVerify createReadTestVerify() {
        return new ReadTestVerify();
    }

    /**
     * Create an instance of {@link LoginCheck }
     * 
     */
    public LoginCheck createLoginCheck() {
        return new LoginCheck();
    }

    /**
     * Create an instance of {@link CreateTestVerify }
     * 
     */
    public CreateTestVerify createCreateTestVerify() {
        return new CreateTestVerify();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link LoginVerify }
     * 
     */
    public LoginVerify createLoginVerify() {
        return new LoginVerify();
    }

    /**
     * Create an instance of {@link ReadTestCheck }
     * 
     */
    public ReadTestCheck createReadTestCheck() {
        return new ReadTestCheck();
    }

    /**
     * Create an instance of {@link LogoutVerify }
     * 
     */
    public LogoutVerify createLogoutVerify() {
        return new LogoutVerify();
    }

    /**
     * Create an instance of {@link DeleteTestVerify }
     * 
     */
    public DeleteTestVerify createDeleteTestVerify() {
        return new DeleteTestVerify();
    }

    /**
     * Create an instance of {@link DeleteTestCheck }
     * 
     */
    public DeleteTestCheck createDeleteTestCheck() {
        return new DeleteTestCheck();
    }

    /**
     * Create an instance of {@link Alternate }
     * 
     */
    public Alternate createAlternate() {
        return new Alternate();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link metier.webapp.persistence.xml.Entry }
     * 
     */
    public metier.webapp.persistence.xml.Entry createEntry() {
        return new metier.webapp.persistence.xml.Entry();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Br }
     * 
     */
    public Br createBr() {
        return new Br();
    }

    /**
     * Create an instance of {@link OutputList.Output }
     * 
     */
    public OutputList.Output createOutputListOutput() {
        return new OutputList.Output();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link OutputMap }
     * 
     */
    public OutputMap createOutputMap() {
        return new OutputMap();
    }

    /**
     * Create an instance of {@link XTemplate }
     * 
     */
    public XTemplate createXTemplate() {
        return new XTemplate();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link Comments }
     * 
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Devices }
     * 
     */
    public Devices createDevices() {
        return new Devices();
    }

    /**
     * Create an instance of {@link Require }
     * 
     */
    public Require createRequire() {
        return new Require();
    }

    /**
     * Create an instance of {@link Language.Entry }
     * 
     */
    public Language.Entry createLanguageEntry() {
        return new Language.Entry();
    }

    /**
     * Create an instance of {@link Tools.Entry }
     * 
     */
    public Tools.Entry createToolsEntry() {
        return new Tools.Entry();
    }

    /**
     * Create an instance of {@link CategoryMap.Category }
     * 
     */
    public CategoryMap.Category createCategoryMapCategory() {
        return new CategoryMap.Category();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "createdDate")
    public JAXBElement<String> createCreatedDate(String value) {
        return new JAXBElement<String>(_CreatedDate_QNAME, String.class, null, value);
    }

}
