//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.24 at 01:06:36 AM CEST 
//


package metier.webapp.presentation.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}metadata" minOccurs="0"/>
 *         &lt;element ref="{}devices" minOccurs="0"/>
 *         &lt;element ref="{}language" minOccurs="0"/>
 *         &lt;element ref="{}text" minOccurs="0"/>
 *         &lt;element ref="{}settings" minOccurs="0"/>
 *         &lt;element ref="{}tools" minOccurs="0"/>
 *         &lt;element ref="{}categoryMap" minOccurs="0"/>
 *         &lt;element ref="{}outputMap" minOccurs="0"/>
 *         &lt;element ref="{}outputList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "devices",
    "language",
    "text",
    "settings",
    "tools",
    "categoryMap",
    "outputMap",
    "outputList"
})
@XmlRootElement(name = "xTemplate")
public class XTemplate {

    protected Metadata metadata;
    protected Devices devices;
    protected Language language;
    protected Text text;
    protected Settings settings;
    protected Tools tools;
    protected CategoryMap categoryMap;
    protected OutputMap outputMap;
    protected OutputList outputList;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the devices property.
     * 
     * @return
     *     possible object is
     *     {@link Devices }
     *     
     */
    public Devices getDevices() {
        return devices;
    }

    /**
     * Sets the value of the devices property.
     * 
     * @param value
     *     allowed object is
     *     {@link Devices }
     *     
     */
    public void setDevices(Devices value) {
        this.devices = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setLanguage(Language value) {
        this.language = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setText(Text value) {
        this.text = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the tools property.
     * 
     * @return
     *     possible object is
     *     {@link Tools }
     *     
     */
    public Tools getTools() {
        return tools;
    }

    /**
     * Sets the value of the tools property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tools }
     *     
     */
    public void setTools(Tools value) {
        this.tools = value;
    }

    /**
     * Gets the value of the categoryMap property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryMap }
     *     
     */
    public CategoryMap getCategoryMap() {
        return categoryMap;
    }

    /**
     * Sets the value of the categoryMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryMap }
     *     
     */
    public void setCategoryMap(CategoryMap value) {
        this.categoryMap = value;
    }

    /**
     * Gets the value of the outputMap property.
     * 
     * @return
     *     possible object is
     *     {@link OutputMap }
     *     
     */
    public OutputMap getOutputMap() {
        return outputMap;
    }

    /**
     * Sets the value of the outputMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputMap }
     *     
     */
    public void setOutputMap(OutputMap value) {
        this.outputMap = value;
    }

    /**
     * Gets the value of the outputList property.
     * 
     * @return
     *     possible object is
     *     {@link OutputList }
     *     
     */
    public OutputList getOutputList() {
        return outputList;
    }

    /**
     * Sets the value of the outputList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputList }
     *     
     */
    public void setOutputList(OutputList value) {
        this.outputList = value;
    }

}
